/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-west-2",
    "aws_cognito_identity_pool_id": "us-west-2:0c065da2-f6f1-4533-9310-9913aed34a7b",
    "aws_cognito_region": "us-west-2",
    "aws_user_pools_id": "us-west-2_lOyCkJKH1",
    "aws_user_pools_web_client_id": "bv9vk0kjp8ptqbcf59u1n7raq",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://24n5qr7ksnabdmkzh5tvgpbwku.appsync-api.us-west-2.amazonaws.com/graphql",
    "aws_appsync_region": "us-west-2",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS"
};


export default awsmobile;
